name: MinecraftDunked
version: '1.5.1'
main: org.zethcodes.bingodunked.BingoDunked
api-version: '1.21.8'
commands:
  bingocard:
    usage: /bingocard
    permission: bingo.bingocard
    aliases: [bc,card]
  bingojoin:
    usage: /bingojoin <team>
    permission: bingo.bingojoin
    aliases: [bj,join]
  bingostart:
    usage: /bingostart [mode] [time]
    permission: bingo.bingostart
    aliases: [bs,start]
  newworld:
    usage: /newworld
    permission: bingo.newworld
    aliases: [ nw ]
  cheat:
    permission: bingo.cheat
    usage: /cheat <slot> [team] [player]
  latejoin:
    usage: /latejoin
    permission: bingo.latejoin
  all:
    usage: /all <message>
    permission: bingo.allchat
  bingotime:
    usage: /bingotime
    permission: bingo.time
    aliases: [ bt ]
  settings:
    usage: /settings
    permission: bingo.settings
  endgame:
    usage: /endgame
    permission: bingo.endgame
permissions:
  bingo.bingocard:
    description: Open your team's bingo card.
    default: true
  bingo.bingojoin:
    description: Join a bingo team. Either 'red', 'blue', 'green' or 'yellow'.
    default: true
  bingo.bingostart:
    description: Start a game of bingo.
    default: true
  bingo.newworld:
    description: Generate a new world for bingo.
    default: true
  bingo.latejoin:
    description: Joins a world late.
    default: true
  bingo.allchat:
    description: Send a message to all players while in-game.
    default: true
  bingo.time:
    description: Tells the player the time remaining.
    default: true
  bingo.settings:
    description: Allows access to Dunked settings.
    default: true
  bingo.endgame:
    description: Ends bingo game.
    default: op
  bingo.cheat:
    description: Allows to autocomplete bingo goals.
    default: op